'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const codec=require('../lib/archive-codec');
const meta=()=>({id:crypto.randomUUID(),instance:crypto.randomUUID(),expiresAt:new Date(Date.now()+86400000).toISOString()});
test('compressed encrypted batches round-trip without plaintext in storage',async()=>{const key=crypto.randomBytes(32),m=meta(),events=Array.from({length:40},(_,i)=>({id:String(i),type:'text',text:'Repetitive private chat message '.repeat(20)}));const packed=await codec.pack(events,key,m);assert.ok(packed.compressedBytes<packed.rawBytes);assert.ok(!packed.payload.toString().includes('private chat'));assert.deepEqual(await codec.unpack(packed.payload,key,m),events);});
test('wrong key, tampering and metadata substitution are rejected',async()=>{const key=crypto.randomBytes(32),m=meta(),p=await codec.pack([{text:'secret'}],key,m);await assert.rejects(codec.unpack(p.payload,crypto.randomBytes(32),m));const bad=Buffer.from(p.payload);bad[bad.length-1]^=1;await assert.rejects(codec.unpack(bad,key,m));await assert.rejects(codec.unpack(p.payload,key,{...m,instance:crypto.randomUUID()}));});
test('view-once media and call streams never enter archive content',()=>{const s={room:'R',username:'U',id:'s'};assert.equal(codec.eventFor(s,'photo',{id:'p',isViewOnce:true,image:'secret'}),null);assert.equal(codec.eventFor(s,'call',{id:'c',audio:Buffer.from('secret')}),null);});
test('normal media is retained as base64 only in the encrypted payload and has size/type guards',()=>{const s={room:'R',username:'U',id:'s'};const data={id:'p',isViewOnce:false,image:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==',caption:'hello'};assert.equal(codec.eventFor(s,'photo',data).mime,'image/gif');assert.throws(()=>codec.eventFor(s,'photo',{...data,image:'https://evil.example/x'}));assert.throws(()=>codec.eventFor(s,'photo',{...data,image:'data:image/svg+xml;base64,PHN2Zz4='}));assert.throws(()=>codec.eventFor(s,'voice',{id:'v',audio:Buffer.alloc(codec.MAX_MEDIA+1)}));});
test('encryption key accepts only a generated 32-byte base64url value',()=>{assert.equal(codec.keyFrom('short'),null);assert.equal(codec.keyFrom(crypto.randomBytes(32).toString('base64url')).length,32);});
