'use strict';
const{test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),{once}=require('node:events');
const{io}=require('socket.io-client');let server,base;const sockets=[];
function event(s,name){return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('Timeout '+name)),4000);s.once(name,d=>{clearTimeout(t);resolve(d);});});}
async function connect(){const s=io(base,{transports:['websocket'],forceNew:true,reconnection:false});sockets.push(s);await event(s,'connect');return s;}
before(async()=>{server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'0',ADMIN_KEY:'',ARCHIVE_DATABASE_URL:'postgresql://unused@127.0.0.1:9/unused',ARCHIVE_ENCRYPTION_KEY:crypto.randomBytes(32).toString('base64url'),ARCHIVE_CLEANUP_TOKEN:''},stdio:['ignore','pipe','pipe']});base=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('Startup timeout')),5000);server.stdout.on('data',d=>{const m=String(d).match(/localhost:(\d+)/);if(m){clearTimeout(t);resolve('http://127.0.0.1:'+m[1]);}});server.once('exit',c=>reject(new Error('Server exited '+c)));});});
after(async()=>{sockets.forEach(s=>s.disconnect());if(server?.exitCode===null){server.kill();await once(server,'exit');}});
test('join page contains a visible retention notice but no acknowledgement checkbox',async()=>{const html=await(await fetch(base+'/')).text();assert.ok(html.includes('archive-retention-notice'));assert.ok(html.includes('up to 7 days'));assert.ok(!html.includes('archive-retention-ack'));assert.ok(!html.includes('archive-ack-label'));});
test('current notice-version marker allows joining without an explicit-consent field',async()=>{const s=await connect();const ready=event(s,'room-ready');s.emit('join-room',{room:'NOTICE',username:'Guest',archiveNoticeVersion:'archive-v1'});assert.equal((await ready).room,'NOTICE');});
test('outdated clients are told to reload, and existing acknowledged v11 clients stay compatible',async()=>{const s=await connect();const denied=event(s,'join-error');s.emit('join-room',{room:'NOTICE',username:'Old'});const d=await denied;assert.match(d.error,/Reload/);assert.ok(!d.error.includes('acknowledge'));const legacy=await connect();const ready=event(legacy,'room-ready');legacy.emit('join-room',{room:'NOTICE',username:'Earlier client',archiveConsent:'archive-v1'});assert.equal((await ready).room,'NOTICE');});
