'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const create=require('../public/push-worker-core');
function fixture(){const map=new Map(),shown=[],opened=[],windows=[];const registration={showNotification:async(t,o)=>shown.push({title:t,...o}),getNotifications:async()=>shown.map(n=>({...n,close(){n.closed=true;}}))};const core=create({store:{all:async()=>[...map.values()],put:async r=>map.set(r.id,r),remove:async id=>map.delete(id),clear:async()=>map.clear()},registration,clients:{matchAll:async()=>windows,openWindow:async url=>opened.push(url)},now:()=>1000});return{core,shown,opened,windows,registration,map};}
const id='a'.repeat(64);const add={type:'binding-add',id,room:'ROOM',expiresAt:100000,previews:true};const payload={type:'room-message',bindings:[id],room:'ROOM',sentAt:1000,title:'Mira',body:'Hi there',eventId:'one'};
test('push works without an open page, with approved sender name/text',async()=>{const f=fixture();await f.core.message(add,{id:'tab-a'});await f.core.push(payload);assert.equal(f.shown[0].title,'Mira');assert.equal(f.shown[0].body,'Hi there');assert.equal(f.shown[0].data.clientId,'tab-a');});
test('Exit/offline local revocation suppresses queued notifications and closes displayed ones',async()=>{const f=fixture();await f.core.message(add,{id:'tab-a'});await f.core.push(payload);await f.core.message({type:'binding-remove',id},{id:'tab-a'});assert.equal(f.shown[0].closed,true);await f.core.push({...payload,eventId:'two'});assert.equal(f.shown.length,1);});
test('cross-room and stale payloads are ignored; opt-out previews are masked',async()=>{const f=fixture();await f.core.message({...add,previews:false},{id:'tab'});await f.core.push({...payload,room:'OTHER'});await f.core.push({...payload,sentAt:-200000});assert.equal(f.shown.length,0);await f.core.push(payload);assert.equal(f.shown[0].title,'TempChat');assert.ok(!f.shown[0].body.includes('Hi there'));});
test('notification click focuses only the originating tab still in that room',async()=>{const f=fixture();await f.core.message(add,{id:'tab-a'});let focused='',message;f.windows.push({id:'wrong',url:'https://example.test/?room=ROOM',focus:async()=>focused='wrong'},{id:'tab-a',url:'https://example.test/?room=ROOM',focus:async()=>focused='correct',postMessage:m=>message=m});await f.core.click({room:'ROOM',clientId:'tab-a',bindings:[id]});assert.equal(focused,'correct');assert.equal(message.type,'notification-click');assert.equal(f.opened.length,0);});
test('closed or changed-room tab opens a room invite without automatically joining',async()=>{const f=fixture();await f.core.message(add,{id:'tab-a'});f.windows.push({id:'tab-a',url:'https://example.test/?room=DIFFERENT'});await f.core.click({room:'ROOM',clientId:'tab-a',bindings:[id]});assert.equal(f.opened[0],'/?room=ROOM');await f.core.message({type:'binding-remove',id},{id:'tab-a'});await f.core.click({room:'ROOM',clientId:'tab-a',bindings:[id]});assert.equal(f.opened.length,1);});
test('platform failures are not reported as success',async()=>{const f=fixture();await f.core.message(add,{id:'tab'});f.registration.showNotification=async()=>{throw new Error('denied');};await assert.rejects(f.core.push(payload),/denied/);});
