'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const create=require('../lib/push-service');
function subscription(suffix='one') {const e=crypto.createECDH('prime256v1');e.generateKeys();return {endpoint:'https://fcm.googleapis.com/fcm/send/'+suffix,keys:{p256dh:e.getPublicKey().toString('base64url'),auth:crypto.randomBytes(16).toString('base64url')}};}
function socket(id,room='ROOM'){const handlers={};return {id,room,username:id,handlers,on:(e,h)=>handlers[e]=h,request(e,d){return new Promise(r=>handlers[e](d,r));}};}
const token=()=>crypto.randomBytes(32).toString('base64url');
function fixture(){let clock=100000;const sent=[];const transport={setVapidDetails(){},async sendNotification(s,p,o){sent.push({s,p:JSON.parse(p),o});}};const service=create({env:{VAPID_PUBLIC_KEY:'public',VAPID_PRIVATE_KEY:'private',VAPID_SUBJECT:'mailto:test@example.com'},transport,now:()=>clock});return {service,sent,transport,advance:ms=>clock+=ms};}
const flush=()=>new Promise(r=>setImmediate(r));
test('only supported HTTPS provider endpoints and proper keys are accepted',()=>{const s=subscription();assert.ok(create.validSubscription(s));for(const endpoint of ['http://fcm.googleapis.com/x','https://127.0.0.1/x','https://fcm.googleapis.com.evil.test/x','https://evilfcm.googleapis.com/x','https://user@fcm.googleapis.com/x','https://fcm.googleapis.com:444/x'])assert.equal(create.validSubscription({...s,endpoint}),null);assert.equal(create.validSubscription({...s,keys:{auth:'a',p256dh:'b'}}),null);});
test('room binding survives socket disconnect; correct name/text push targets only that room',async()=>{const f=fixture(),a=socket('a'),b=socket('b');f.service.attach(b);const result=await b.request('push-register',{token:token(),subscription:subscription(),foreground:false,previews:true});assert.ok(result.ok);f.service.disconnect(b);f.service.notify(socket('x','OTHER'),{id:'wrong',title:'X',body:'secret'});assert.equal(f.sent.length,0);f.service.notify(a,{id:'msg',title:'Alice',body:'Hello phone'});await flush();assert.equal(f.sent[0].p.title,'Alice');assert.equal(f.sent[0].p.body,'Hello phone');assert.ok(f.sent[0].p.bindings.includes(result.id));assert.equal(f.sent[0].o.TTL,120);f.service.close();});
test('foreground and sender self notifications are suppressed, explicit Exit revokes alerts',async()=>{const f=fixture(),a=socket('a'),b=socket('b'),t=token();f.service.attach(b);await b.request('push-register',{token:t,subscription:subscription(),foreground:true});f.service.notify(a,{id:'1',title:'A',body:'one'});assert.equal(f.sent.length,0);b.handlers['push-presence']({token:t,foreground:false});f.service.notify(b,{id:'2',title:'B',body:'self'});assert.equal(f.sent.length,0);f.service.leave(b);f.service.notify(a,{id:'3',title:'A',body:'afterexit'});await flush();assert.equal(f.sent.length,0);f.service.close();});
test('same-browser duplicate tabs receive one push; previews can be hidden',async()=>{const f=fixture(),s=subscription(),b=socket('b'),c=socket('c');for(const x of [b,c]){f.service.attach(x);await x.request('push-register',{token:token(),subscription:s,previews:false});}f.service.notify(socket('a'),{id:'1',title:'Private name',body:'Private body'});await flush();assert.equal(f.sent.length,1);assert.equal(f.sent[0].p.bindings.length,2);assert.equal(f.sent[0].p.title,'TempChat');assert.ok(!f.sent[0].p.body.includes('Private'));f.service.close();});
test('expired/provider-gone subscriptions are pruned and reset revokes room',async()=>{const f=fixture(),b=socket('b');f.service.attach(b);await b.request('push-register',{token:token(),subscription:subscription()});f.advance(86400001);f.service.notify(socket('a'),{id:'old',title:'A',body:'old'});assert.equal(f.sent.length,0);await b.request('push-register',{token:token(),subscription:subscription('new')});f.service.reset('ROOM');f.service.notify(socket('a'),{id:'reset',title:'A',body:'reset'});assert.equal(f.sent.length,0);f.advance(2000);await b.request('push-register',{token:token(),subscription:subscription('gone')});f.transport.sendNotification=async()=>{throw {statusCode:410};};f.service.notify(socket('a'),{id:'gone',title:'A',body:'gone'});await flush();f.transport.sendNotification=async()=>{throw new Error('Should not be called again');};f.service.notify(socket('a'),{id:'gone2',title:'A',body:'gone2'});f.service.close();});
test('unconfigured server returns explicit error and never exposes private key',async()=>{const service=create({env:{}}),s=socket('s');service.attach(s);const result=await s.request('push-register',{token:token(),subscription:subscription()});assert.match(result.error,/not configured/);assert.equal(service.config().configured,false);assert.equal(service.config().publicKey,null);assert.equal(JSON.stringify(service.config()).includes('VAPID_PRIVATE_KEY'),false);service.close();});
test('arbitrary tokens cannot revoke another room binding',async()=>{const f=fixture(),b=socket('b');f.service.attach(b);await b.request('push-register',{token:token(),subscription:subscription()});f.service.unregister(token());f.service.notify(socket('a'),{id:'1',title:'A',body:'Hello'});await flush();assert.equal(f.sent.length,1);f.service.close();});
test('optional durable subscription store survives restart without storing message text',async()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tempchat-push-test-')),file=path.join(dir,'subscriptions.json');
 const sent=[];const transport={setVapidDetails(){},async sendNotification(s,p){sent.push(JSON.parse(p));}};
 const env={VAPID_PUBLIC_KEY:'public',VAPID_PRIVATE_KEY:'private',VAPID_SUBJECT:'mailto:test@example.com',PUSH_STORE_PATH:file};
 const first=create({env,transport}),b=socket('b');first.attach(b);const t=token();await b.request('push-register',{token:t,subscription:subscription(),foreground:true});
 await new Promise(r=>setTimeout(r,220));first.close();
 const saved=fs.readFileSync(file,'utf8');assert.ok(!saved.includes(t));assert.ok(!saved.includes('socketId'));
 const second=create({env,transport});assert.equal(second.config().durable,true);second.notify(socket('a'),{id:'afterrestart',title:'A',body:'New message'});await flush();assert.equal(sent.length,1);second.close();fs.rmSync(dir,{recursive:true,force:true});
});
test('stale foreground heartbeat does not suppress suspended-phone alerts forever',async()=>{const f=fixture(),b=socket('b');f.service.attach(b);await b.request('push-register',{token:token(),subscription:subscription(),foreground:true});f.advance(30001);f.service.notify(socket('a'),{id:'1',title:'A',body:'Wake-up'});await flush();assert.equal(f.sent.length,1);f.service.close();});
test('device-off revokes same endpoint bindings but not another device',async()=>{const f=fixture(),shared=subscription('shared'),tokens=[];for(const [name,sub] of [['b',shared],['c',shared],['d',subscription('separate')]]){const s=socket(name);f.service.attach(s);const t=token();tokens.push(t);await s.request('push-register',{token:t,subscription:sub});}f.service.disableDevice(tokens[0]);f.service.notify(socket('a'),{id:'1',title:'A',body:'Hello'});await flush();assert.equal(f.sent.length,1);assert.match(f.sent[0].s.endpoint,/separate$/);f.service.close();});
